serviceConfig:
  scheme: http://
  hostName:
  port: 
  path: /api/idm

loggerConfig:
  outputDir: ./logs/
  outputFile: idm.log

databaseConfig:
  dbUsername:
  dbPassword: 
  dbHostname: localhost
  dbPort: 3306
  dbDriver: com.mysql.cj.jdbc.Driver
  dbName: 
  dbSettings: ?autoReconnect=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=PST

sessionConfig:
  expiration: 24000
  timeout: 20000
