serviceConfig:
  scheme: http://
  hostName:
  port: 
  path: /api/billing

loggerConfig:
  outputDir: ./logs/
  outputFile: billing.log

databaseConfig:
  dbUsername:
  dbPassword: 
  dbHostname: 
  dbPort: 3306
  dbDriver: com.mysql.cj.jdbc.Driver
  dbName:
  dbSettings: ?autoReconnect=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=PST